//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salesCRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int id { get; set; }
        public string customerId { get; set; }
        public string employeeid { get; set; }
        public int orderId { get; set; }
        public int opportunityId { get; set; }
        public int price { get; set; }
        public System.DateTime dateCreated { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual Opportunity Opportunity { get; set; }
        public virtual orderProduct orderProduct { get; set; }
    }
}
