//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salesCRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lead()
        {
            this.leaddetails = new HashSet<leaddetail>();
            this.Opportunities = new HashSet<Opportunity>();
        }
    
        public int id { get; set; }
        public string CustomerId { get; set; }
        public string employeeId { get; set; }
        public string leadOwner { get; set; }
        public string leadSource { get; set; }
        public string leadTopic { get; set; }
        public string leadStatus { get; set; }
        public string leadStage { get; set; }
        public string leadBudget { get; set; }
        public System.DateTime generateddate { get; set; }
        public System.DateTime terminateddate { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leaddetail> leaddetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opportunity> Opportunities { get; set; }
    }
}
